param(
    [switch]$Force
)

$envFile = Join-Path $PSScriptRoot "..\.env"

if ((Test-Path $envFile) -and (-not $Force)) {
    Write-Host ".env already exists. Use -Force to overwrite." -ForegroundColor Yellow
    return
}

function Find-App {
    param(
        [string]$Name,
        [string[]]$Paths
    )
    
    # 1. Check if in PATH
    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    
    # 2. Check specified paths
    foreach ($p in $Paths) {
        if ($p -and (Test-Path $p)) { return $p }
    }
    
    return "NOT_FOUND"
}

Write-Host "Detecting application paths..." -ForegroundColor Cyan

$local = $env:LOCALAPPDATA

$apps = @{
    "WT_PATH"          = Find-App "wt" @(Join-Path $local "Microsoft\WindowsApps\wt.exe")
    "PWSH_PATH"        = Find-App "pwsh" @()
    "GITBASH_PATH"     = Find-App "git-bash" @("C:\Program Files\Git\git-bash.exe", "C:\Program Files (x86)\Git\git-bash.exe")
    "VSCODE_PATH"      = Find-App "code.exe" @(
                            (Join-Path $local "Programs\Microsoft VS Code\Code.exe"),
                            "C:\Program Files\Microsoft VS Code\Code.exe"
                         )
    "WARP_PATH"        = Find-App "warp.exe" @(Join-Path $local "Programs\Warp\warp.exe")
    "ANTIGRAVITY_PATH" = Find-App "antigravity.exe" @(
                            (Join-Path $local "Programs\Antigravity\Antigravity.exe"),
                            "C:\Program Files\Antigravity\antigravity.exe"
                         )
    "POWERRENAME_PATH" = Find-App "PowerToys.PowerRename" @(
                            "C:\Program Files\PowerToys\PowerToys.PowerRename.exe",
                            "C:\Program Files\PowerToys\PowerRename\PowerToys.PowerRename.exe",
                            (Join-Path $local "PowerToys\WinUI3Apps\PowerToys.PowerRename.exe"),
                            (Join-Path $local "PowerToys\PowerToys.PowerRename.exe")
                         )
}

$content = "# Auto-generated by setup-env.ps1`n"
$apps.GetEnumerator() | Sort-Object Name | ForEach-Object {
    $content += "$($_.Key)=$($_.Value)`n"
    if ($_.Value -eq "NOT_FOUND") {
        Write-Host "[-] Could not find path for $($_.Key)" -ForegroundColor Red
    } else {
        Write-Host "[+] Found $($_.Key): $($_.Value)" -ForegroundColor Green
    }
}

Set-Content -Path $envFile -Value $content -Encoding utf8
Write-Host "`nEnvironment file created at: $envFile" -ForegroundColor Cyan
